spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev     #开发环境
  application: 
    name: microservicecloud-config-hfbin-dev
---
spring:
  profiles: test   #测试环境
  application: 
    name: microservicecloud-config-hfbin-test